#ifndef main_
#define main_
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <pthread.h>
#include <arpa/inet.h>

#include "structs.h"
#include "nameserver/create.h"
#include "nameserver/nm.h"
#include "nameserver/view.h"
#include "nameserver/read.h"
#include "clientt/client.h"
#include "clientt/read.h"
#include "clientt/write.h"
#include "storageserver/ss.h"
#include "storageserver/read.h"
#include "storageserver/write.h"
#include "nameserver/write.h"
#include "nameserver/getAddInfo.h"
#include "storageserver/undo.h"
#include "nameserver/undo.h"
#include "nameserver/checkpoint.h"
#include "nameserver/listcheckpoint.h"
#include "nameserver/delete.h"
#include "nameserver/list.h"
#include "nameserver/addaccess.h"
#include "nameserver/removeaccess.h"
#include "nameserver/folder.h"
#include "nameserver/path.h"
#include "nameserver/exec.h"
#include "storageserver/exec.h"
#include "nameserver/stream.h"
#include "storageserver/stream.h"
#include "clientt/exec.h"
#include "clientt/stream.h"
#include "storageserver/persist.h"
#include "error_codes.h"
#include "storageserver/log.h"
#include "nameserver/log.h"
#include "clientt/viewcheckpoint.h"
#include "nameserver/viewcheckpoint.h"
#include "nameserver/revert.h"
#include "clientt/revert.h"
#include "nameserver/access_control.h"
#endif